on:
  push:
    branches:
    - main
env:
  buildConfiguration: Release
  pluginFolder: Nop.Plugin.Admin.StyleEditor
  pluginSystemName: Admin.StyleEditor
  githubProjectName: NOP-Plugin-StyleEditor
  build_4_30: true
  build_4_40: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: Bungalow64/NOP-Plugin-StyleEditor
    - uses: actions/checkout@v2
      with:
        repository: Bungalow64/NOP-4.30
      if: (success() && ('${{ env. variables.build_4_30  }}' == true))
    - uses: actions/checkout@v2
      with:
        repository: Bungalow64/NOP-4.40
      if: (success() && ('${{ env. variables.build_4_40  }}' == true))
    - uses: actions/checkout@v2
      with:
        repository: Bungalow64/NOP-4.50
    - name: List contents of ${{ github.workspace }}
      run: Get-ChildItem -Path '${{ github.workspace }}' -recurse
      shell: powershell
    - name: dotnet build ${{ env.buildConfiguration }} - NOP 4.30
      run: dotnet build ${{ github.workspace }}/NOP-4.30/**/*.sln --configuration ${{ env.buildConfiguration }}
      if: (success() && ('${{ env. variables.build_4_30  }}' == true))
    - name: dotnet build ${{ env.buildConfiguration }} - NOP 4.40
      run: dotnet build ${{ github.workspace }}/NOP-4.40/**/*.sln --configuration ${{ env.buildConfiguration }}
      if: (success() && ('${{ env. variables.build_4_40  }}' == true))
    - name: dotnet build ${{ env.buildConfiguration }} - NOP 4.50
      run: dotnet build ${{ github.workspace }}/NOP-4.50/**/*.sln --configuration ${{ env.buildConfiguration }}
    - name: dotnet test - NOP 4.30
      run: dotnet test ${{ github.workspace }}/NOP-4.30/**/CustomPlugins/${{ env.pluginFolder }}/**/*.Tests.csproj
      if: (success() && ('${{ env. variables.build_4_30  }}' == true))
    - name: dotnet test - NOP 4.40
      run: dotnet test ${{ github.workspace }}/NOP-4.40/**/CustomPlugins/${{ env.pluginFolder }}/**/*.Tests.csproj
      if: (success() && ('${{ env. variables.build_4_40  }}' == true))
    - name: dotnet test - NOP 4.50
      run: dotnet test ${{ github.workspace }}/NOP-4.50/**/CustomPlugins/${{ env.pluginFolder }}/**/*.Tests.csproj
    - name: Check and create directory - 4.30
      run: If (!(Test-Path '${{ github.workspace }}/4.30/${{ env.pluginSystemName }}')) { New-Item -Path '${{ github.workspace }}/4.30/${{ env.pluginSystemName }}' -ItemType Directory }
      shell: powershell
      if: (success() && ('${{ env. variables.build_4_30  }}' == true))
    - name: Check and create directory - 4.40
      run: If (!(Test-Path '${{ github.workspace }}/4.40/${{ env.pluginSystemName }}')) { New-Item -Path '${{ github.workspace }}/4.40/${{ env.pluginSystemName }}' -ItemType Directory }
      shell: powershell
      if: (success() && ('${{ env. variables.build_4_40  }}' == true))
    - name: Check and create directory - 4.50
      run: If (!(Test-Path '${{ github.workspace }}/4.50/${{ env.pluginSystemName }}')) { New-Item -Path '${{ github.workspace }}/4.50/${{ env.pluginSystemName }}' -ItemType Directory }
      shell: powershell
    - name: Copy manifest file
      run: Copy-Item -Path '${{ github.workspace }}\${{ env.githubProjectName }}\package\uploadedItems.json' -Destination '${{ github.workspace }}'
      shell: powershell
    - name: Copy plugin - 4.30
      run: Copy-Item -Path '${{ github.workspace }}\NOP-4.30\Presentation\Nop.Web\Plugins\${{ env.pluginSystemName }}\*' -Destination '${{ github.workspace }}\4.30\${{ env.pluginSystemName }}' -Recurse
      shell: powershell
      if: (success() && ('${{ env. variables.build_4_30  }}' == true))
    - name: Copy plugin - 4.40
      run: Copy-Item -Path '${{ github.workspace }}\NOP-4.40\src\Presentation\Nop.Web\Plugins\${{ env.pluginSystemName }}\*' -Destination '${{ github.workspace }}\4.40\${{ env.pluginSystemName }}' -Recurse
      shell: powershell
      if: (success() && ('${{ env. variables.build_4_40  }}' == true))
    - name: Copy plugin - 4.50
      run: Copy-Item -Path '${{ github.workspace }}\NOP-4.50\src\Presentation\Nop.Web\Plugins\${{ env.pluginSystemName }}\*' -Destination '${{ github.workspace }}\4.50\${{ env.pluginSystemName }}' -Recurse
      shell: powershell
    - name: List contents of ${{ github.workspace }}
      run: Get-ChildItem -Path '${{ github.workspace }}' -recurse
      shell: powershell
      name: Generate zip file
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ${{ github.workspace }}\${{ env.pluginSystemName }}_${{ github.run_id }}.zip ${{ github.workspace }}
    - name: Publish zip file
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}\${{ env.pluginSystemName }}_${{ github.run_id }}.zip
        name: GeneratedPackage
                    